### ISSUE TITLE
FR: sampling and filtering

### ISSUE THREAD

**Issue by eosborne-newrelic** [kentik/ktranslate#240]
...might really be two separate FRs.

sampling: most modern routers support some form of flow sampling, so that what's sent to a flow collector is only 1:N packets.  Opnsense does not. I am running opnsense as a firewall (it makes a decent home hacker/branch office-type device) and as I am sending every flow to kproxy and then up to New Relic, I'm burning 1GB+/day of ingest bandwidth just for kflow.  This is a lot. It would be really nice to have something like a 1:N downsampling knob in kproxy.

filtering: My home architecture is something like

`[cable modem]---[firewall]---[home LAN]---[kproxy box]`

I am afraid, although I have not taken the time prove it, that a substantial number of flows recorded by the firewall are in fact flows from the kproxy container out to New Relic.  This seems rather...suboptimal. Ideally I'd attach the kproxy box to the firewall on a different interface, but that would break other things in my house.  Does kproxy do anything to try and filter out flows that it sees of flows that it sends up to NR One?  If not, that'd be cool.

**Comment by Mesverrum** [comment]
Even in consulting at big enterprises I often found the communication going to the flow collector as being one of the top 20 or so destinations because it is a consistent and moderately sized stream of data, that's just how the protocol is.  I feel like filtering out the communication involving flow collection or sending it to NR would just introduce a blind spot to customers.  I wouldn't be surprised if this data represented something in the range of 1-5% of the traffic passing through a customer's network device so it would be a disservice to users to just not tell them that, it's important information they need to property size their connections and know what is on them.

On the topic of sampling, I think @i3149 would be best to answer if that's practical to implement on this end.  As a general rule I prefer that data gets filtered before it goes across the network instead of just dropping it at the destination. As you mention, nearly all enterprise hardware already has built in sampling capabilities.  This looks to just be a limitation of ng_netflow to not do sampling, might be something best addressed with the opnsense maintainers?

**Comment by i3149** [comment]
There is a 

```
   -sample_rate int
    	Sampling rate to use. 1 -> 1:1 sampling, 2 -> 1:2 sampling and so on.
```
 Flag which ktranslate supports. By default when the macro `nr1.flow` is used it defaults to 1000 but any value can be set.

Separately, are you talking about `ktranslate` or `kproxy`? Kproxy is a closed source tool kentik publishes. Questions about this tool are best directed to support@kentik.com. This repo is just for ktranslate which is open source.

**Comment by i3149** [comment]
Practically speaking, kentik usually directs people to use https://github.com/sleinen/samplicator to sample packets down when the flow exporting device doesn't directly support this.
