### ISSUE TITLE
Feat: Enable DNS by default on AWS VPC flow lambda

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#277]
Noticed that host resolution is not enabled for VPC flows.  
Is there an environmental variable we can set when we set up the lambda that would enable it?
It would be beneficial if the lambda could look up its own dns settings, maybe by parsing it from/etc/resolv.conf instead of beig a hard coded flag.

**Comment by i3149** [comment]
Makes sense. Resolver code is here: https://github.com/kentik/ktranslate/blob/main/pkg/cat/resolver.go

Right now it asks for an IP address of an external resolver. What I'd be tempted to do is modify this so that it can also just use https://pkg.go.dev/net#LookupIP and the host's resolver service directly. This should be able to get the right info for the VPC case.
