### ISSUE TITLE
 SNMP Profile mounted to docker containers gets changed to directory

### ISSUE THREAD

**Issue by BalajiTechs** [kentik/ktranslate#327]
I have noticed strange issue. Not confirmed yet but the file mounted to docker containers gets changed to directory when the machine restarted without stopping the container. 

This is how i start the agent
```
docker run -ti --name ktranslate-discovery --rm --net=host --user `id -u`:`id -g` \
-v /var/tmp/snmp-base.yaml:/snmp-base.yaml kentik/ktranslate:v2     \
-snmp /snmp-base.yaml     -log_level info     \
-snmp_discovery=true


docker rm ktranslate-snmp -f
#Start monitoring devices
docker run -d --name ktranslate-snmp --restart unless-stopped --net=host \
-v /var/tmp/snmp-base.yaml:/snmp-base.yaml \
-e NEW_RELIC_API_KEY=some_key  \
kentik/ktranslate:v2   \
-snmp /snmp-base.yaml   -nr_account_id=account_id   -log_level=info   -metrics=jchf   -tee_logs=true   -service_name=snmp   nr1.snmp
```

```
[root@localhost vmuser]# docker ps --all
CONTAINER ID   IMAGE                  COMMAND                  CREATED       STATUS                     PORTS     NAMES
3f4aff31e926   kentik/ktranslate:v2   "ktranslate -listen …"   6 weeks ago   Exited (127) 10 days ago             ktranslate-snmp
[root@localhost vmuser]# docker restart 3f4aff31e926
Error response from daemon: Cannot restart container 3f4aff31e926: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/var/tmp/snmp-base.yaml" to rootfs at "/snmp-base.yaml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

Is this a known issue or I am doing something wrong here.?

**Comment by i3149** [comment]
This is the side affect of how docker handles volume mounts. If a volume mount does't exist on the host OS, docker will create it as an empty directory. See https://docs.docker.com/storage/bind-mounts/ for more info on this. 

My guess is that `/var/tmp/snmp-base.yaml` doesn't exist after reboot, because its a tmpfs volume.  Docker will run the container because `--restart unless-stopped` flag is set when the host boots up. Because there's no file, docker tries to be helpful and create a directory, which is what leads you into this problem. 

The best advice is to place your `snmp-base.yaml` file on persistent storage which will survive across a reboot. If you don't have any persistent storage on this host you can also place it on an aws s3 bucket by referencing it like `-snmp s3://my-bucket/path-to-my-object-snmp-base.yaml` on the command line. 

Cheers

**Comment by BalajiTechs** [comment]
@i3149  Silly me. Now it makes sense. Thanks for detailed explanation.
