### ISSUE TITLE
Influx measurement structure

### ISSUE THREAD

**Issue by i3149** [kentik/ktranslate#363]
Currently all SNMP values collected in ktranslate are reported in one of two “measurements” in influx format: `kentik.snmp.device` and `kentik.snmp.interface`. This should be restructured so that named measurements correspond to the subobjects (e.g., interfaces, VLANs, BGP peers, etc.) within a device.

When a measurement line is sent it should include all of the tags and fields for that particular subobject. This will help support most efficient storage and query.

**Comment by dpajin-kentik** [comment]
InfluxDB sink for SNMP collected data produce only two measurements:

- kentik.snmp.interface - which contains tags and metrics related to the device network interfaces
- kentik.snmp.device - contains all the tags and metrics from all other measurement, including scalars, but also tables

The example of the outputs of the kentik.snmp.device:

```markdown
# tags and metrics from the host-resources-mib.yml, hrStorageTable
kentik.snmp.device,device_name=ktranslate,eventType=KSnmpDeviceMetric,SysObjectID=.1.3.6.1.4.1.8072.3.2.10,SysName=dpajin-xps,storage_description=/run/snapd/ns,provider=kentik-net-snmp,Index=.113,src_addr=127.0.0.1,SysServices=0,storage_type=.1.3.6.1.2.1.25.2.1.4 hrStorageUsed=733,hrStorageSize=815386,hrStorageAllocationUnits=4096 1658314621000000000

# Tags and metrics from the ucd-mib.yml, diskIOTable
kentik.snmp.device,eventType=KSnmpDeviceMetric,SysName=dpajin-xps,diskIO_device=loop10,device_name=ktranslate,Index=.23,src_addr=127.0.0.1,provider=kentik-net-snmp,SysObjectID=.1.3.6.1.4.1.8072.3.2.10,SysServices=0 diskIONReadX=1850368,diskIOReads=417,diskIOWrites=0,diskIONWrittenX=0,diskIOLA5=0,diskIOLA1=0,diskIOLA15=0 1658314621000000000

# Tags and metrics from both hrStorageTable and diskIOTable combined in one record
# I guess the reason for this is the same "Index" value of the row from both tables
kentik.snmp.device,eventType=KSnmpDeviceMetric,SysName=dpajin-xps,Index=.3,storage_type=.1.3.6.1.2.1.25.2.1.3,provider=kentik-net-snmp,src_addr=127.0.0.1,SysServices=0,SysObjectID=.1.3.6.1.4.1.8072.3.2.10,diskIO_device=loop2,device_name=ktranslate diskIOLA15=0,hrStorageUsed=12470428,hrStorageSize=34712576,diskIONReadX=1121280,hrStorageAllocationUnits=1024,diskIOReads=59,diskIOWrites=0,diskIONWrittenX=0,diskIOLA5=0,diskIOLA1=0 1658314621000000000

```

Definition from the snmp_profiles of the **hrStorageTable:**

```markdown
- MIB: HOST-RESOURCES-MIB
    table:
      OID: 1.3.6.1.2.1.25.2.3
      name: **hrStorageTable**
    symbols:
      - OID: 1.3.6.1.2.1.25.2.3.1.4
        name: hrStorageAllocationUnits
      - OID: 1.3.6.1.2.1.25.2.3.1.5
        name: hrStorageSize
      - OID: 1.3.6.1.2.1.25.2.3.1.6
        name: hrStorageUsed
      - OID: 1.3.6.1.2.1.25.2.3.1.7
        name: hrStorageAllocationFailures
    metric_tags:
      - tag: **storage_description**
        column:
          OID: 1.3.6.1.2.1.25.2.3.1.3
          name: hrStorageDescr
      - tag: **storage_type**
        column:
          OID: 1.3.6.1.2.1.25.2.3.1.2
          name: hrStorageType
```

Definition from the snmp_profiles of the **diskIOTable:**

```markdown
# Table of IO devices and how much data they have read/written.
  - MIB: UCD-DISKIO-MIB
    table:
      OID: 1.3.6.1.4.1.2021.13.15.1.1
      name: **diskIOTable**
    symbols:
      # The number of read accesses from this device since boot.
      - name: diskIOReads
        OID: 1.3.6.1.4.1.2021.13.15.1.1.5
      # The number of write accesses to this device since boot.
      - name: diskIOWrites
        OID: 1.3.6.1.4.1.2021.13.15.1.1.6
      # The 1 minute average load of disk (%)
      - name: diskIOLA1
        OID: 1.3.6.1.4.1.2021.13.15.1.1.9
      # The 5 minute average load of disk (%)
      - name: diskIOLA5
        OID: 1.3.6.1.4.1.2021.13.15.1.1.10
      # The 15 minute average load of disk (%)
      - name: diskIOLA15
        OID: 1.3.6.1.4.1.2021.13.15.1.1.11
      # The number of bytes read from this device since boot. (64-bit counter)
      - name: diskIONReadX
        OID: 1.3.6.1.4.1.2021.13.15.1.1.12
      # The number of bytes written to this device since boot. (64-bit counter)
      - name: diskIONWrittenX
        OID: 1.3.6.1.4.1.2021.13.15.1.1.13
    metric_tags:
      # The name of the device we are counting/checking.
      - tag: **diskIO_device**
        column:
          name: diskIODevice
          OID: 1.3.6.1.4.1.2021.13.15.1.1.2
```

### What needs to be done/changed:

We need to change the behavior of the InfluxDB sync so that:

- Only scalar OIDs will be exported in the “device” measurement
    - There are probably some scalar metrics that we would like to group/push to separate measurement names, but this will be covered with the metrics_profiles rework.
- Each table OID definition should be exported in its own measurement

Considering the snmp profile definitions for the previously discussed tables, they should be organized in the measurements in the following way:

```markdown
# tags and metrics from the host-resources-mib.yml, hrStorageTable
**hrStorageTable**,device_ip=127.0.0.1,device_name=dpajin-xps,index=.113,**storage_description**=/run/snapd/ns,**storage_type**=.1.3.6.1.2.1.25.2.1.4 hrStorageUsed=733,hrStorageSize=815386,hrStorageAllocationUnits=4096 1658314621000000000

# Tags and metrics from the ucd-mib.yml, diskIOTable
**diskIOTable**,device_ip=127.0.0.1,device_name=dpajin-xps,index=.23,**diskIO_device**=loop10 diskIONReadX=1850368,diskIOReads=417,diskIOWrites=0,diskIONWrittenX=0,diskIOLA5=0,diskIOLA1=0,diskIOLA15=0 1658314621000000000

```

For each of these measurements, we need to have a “predefined” tag name which would uniquely point to the “device”, so that we can know, from which device it comes from. We should add the following two tags always:

- **device_ip** - tag that we use for device IP address used for SNMP polling and that can be one of the guaranteed unique device IDs
- **device_name** - maybe we need this one too, if we consider scenarios of the companies merging or having overlapping IP address spaces in some parts of the network.

We should remove the following tags which are included at the moment:

- **device_name**=ktranslate  → is this collector name - we should remove it and use it differently:
  - maybe we want to rename it to **collector_name?**
  - can we make this configurable, to export "collector_name" tag which would contain the hostname of the ktranslate instance. maybe we want to have this, so that we know from which instance it is coming from, maybe important in big setups with many collectors
- **eventType**=KSnmpDeviceMetric - remove
- **SysObjectID**=.1.3.6.1.4.1.8072.3.2.10 - remove
- **provider**=kentik-net-snmp - remove it for not:
  - in the future, maybe want to have a notion of the “**collection_method**” as the protocol that it is coming from?
- **SysServices**=0 - remove
- rename “Index” to “index” - small “i”

- Names of the measurements:
    - we should remove “kentik.snmp” prefix, not sure why we would need it.
    - We can maybe add a configuration option for “influxdb_measurement_prefix” that would glued for these names and empty by default, but not necessary at the moment.
    - We should use the predefined name “device” for measurements related to the device scalar metrics

**Comment by i3149** [comment]
I think this is mostly good now.
