### ISSUE TITLE
HTTP_PROXY

### ISSUE THREAD

**Issue by TobyKnight** [kentik/ktranslate#622]
I have been testing the Docker Container and the PAckage Manager Install, I have found that the HTTP_PROXY environment variable is ignored. I setup an environment with both an HTTP and HTTPS proxy. The HTTPS_PROXY environment setting works as expected. The HTTP_PROXY is ignored. This also occurs in the Package Manager Install in the ktranslate.env file.

The docker run command include the flag -e HTTP_PROXY=http://testproxy:80 which fails whilst HTTPS_PROXY=https://testproxy:443 works as expected. The ktranslate.env file includes HTTP_PROXY=http:\\testproxy:80 which fails and HTTPS_PROXY=https:\\testproxy:443 which works as expected

The OS is RHEL 8.6. the version of ktranslate is the current version

**Comment by i3149** [comment]
I'm pretty sure this is go acting how its supposed to work. See https://pkg.go.dev/net/http#ProxyFromEnvironment. 

This value is explicitly set in https://github.com/kentik/ktranslate/blob/main/pkg/sinks/nr/nr.go#L153

Because all requests are over HTTPS, go will not use the `HTTP_PROXY` for these. If there's docs saying that `HTTP_PROXY` should be set, these should be updated to reference `HTTPS_PROXY`

**Comment by i3149** [comment]
One thing to try is set -e HTTP_PROXY=[https://testproxy:443](https://testproxy/) I think this will work because you're not de-crypting https traffic.

**Comment by TobyKnight** [comment]
That makes sense.

The doco is in the New Relic quickstart for both the docker version and the
package manager version


There is a proxy toggle with a HTTP_PROXY option. This then generates the
docker run and the env file with a HTTP_PROXY.

This probably needs to be updated

Thanks for looking at it

Toby
