### ISSUE TITLE
Adding optional meraki bw limit info

### ISSUE THREAD

**Issue by Rajupln917** [kentik/ktranslate#718]
When we try to set the preference provided in the below issue, it completely stopped reporting data for that Meraki org with no errors in the logs.

preferences:
show_uplink_bandwidth_limits: true

Issue refernce link: https://github.com/kentik/ktranslate/pull/686

Please check on this.

**Comment by i3149** [comment]
The problem here is that this call is per network, not per organization like all of the others. This means iterating over all the networks you have while respecting the API timing limits meraki enforces. End result is that things can take a long time when there are a non trivial number of networks to go over. 

Looking at the code, there's a cache so that subsequent calls will be fast, but the first time around will take a long time and block results, which is what you are seeing. Let me try to have it load the data in the background without blocking results. Then when the data is set, it will show up in the results. Seem resonable?

**Comment by Rajupln917** [comment]
Yes, that helps! when you shift the data load to the back ground
