### ISSUE TITLE
SD-WAN Setup

### ISSUE THREAD

**Issue by wildcardlinux** [kentik/ktranslate#729]
Wanted to reopen https://github.com/kentik/ktranslate/issues/719 but opened new issue:

Thank you, we are trying to monitor about 6400 devices and they are static ip'ed so after the discovery we could remove the ranges if that would help. Is it a requirement that the container be on the LAN with devices? We are trying to monitor them over sd-wan connections with avg 30msec latency, how big of an issue could that be? Is there a way to know if that is causing the NULL value issues?

**Comment by i3149** [comment]
No requirement to be on the same lan, 30msec should be fine. Since everything is static maybe just skip the discovery process entirely? Generate the yaml for each device yourself and then just run ktrans for doing the snmp polling? I'd recommend sticking to around 50 devices per CPU core you have available.  Can also ask on https://discord.com/channels/887507000722882570/888243620367458374 and see if any other practitioners have advice.
