### ISSUE TITLE
SNMP Quickstart ktranslate docker commands fail if you have spaces in file path

### ISSUE THREAD

**Issue by keeb-dev** [kentik/ktranslate#98]

**Comment by nickstinemates** [comment]
The default `docker run` command that is in the SNMP Quickstart wiki article fails due to the installation path and path of configuration files in `C:\Program Files(x86)\KTranslate`. The spaces cause the commandline parser to misinterpret the intent. Specifically the volume mounting `-v` flag.

Likely need to surround the path with `"` by default to ensure this doesn't occur.
